ado:
  organization: rickywck
  project: rde-lab
  pat_env_var: ADO_PAT

pinecone:
  api_key_env_var: PINECONE_API_KEY
  index_name: rde-lab
  environment: us-east-1
  project: poc

openai:
  api_key_env_var: OPENAI_API_KEY
  embedding_model: text-embedding-3-small
  chat_model: gpt-4o-mini
  embedding_dimensions: 512

retrieval:
  ado:
    top_k: 5
    min_similarity_threshold: 0.5
  architecture:
    top_k: 5
    min_similarity_threshold: 0.5
  tagging:
    min_similarity_threshold: 0.5


generation:
  max_ado_in_prompt: 6
  max_arch_in_prompt: 6
  ado_desc_len: 400
  arch_text_len: 600
  max_tokens: 2000
